# =========================
# CONFIGURACIÓN DEL PIPELINE
# =========================

night: "20250823bis"
filters: ["I", "V"]  # filtros a procesar

paths:
  BASE: "/home/knowogrodski/Documentos/observation_HSH/ulens_hsh/ulens_hsh"
  data_dir: "data"           
  objects_dir: "objetos"
  objects_file: "objetos.csv"
  images_data_file: "images_data.csv"          


instrument:
  gain: 2.0
  rdnoise: 15.7

steps:
  update_headers: true
  export_metadata: true
  reduction: true
  astrometry: false
  contains_obj: true
  combine: true
  cleanup: false
  plots: false

reduction:
  zero_correction: true
  flat_correction: true
  dark_correction: false   # aún no implementado

astrometry:
  method: "astrometrynet"
  api_key: "wuupmjpswkcbncws"   # para API externa
  overwrite: false

aligment: 
  catalog:
    use_catalogs: "all"  # "all" o lista de catálogos
    min_mag: 9
    max_mag: 12
    fov_frac: 0.3  # fracción del FOV para búsqueda de
    plot: true
    overwrite: true


combine:
  combine_method: "median"  # "average" o "median"
  reject_method: "minmax"   # "minmax" o "sigma"
  nlow: 1                    # para "minmax"
  nhigh: 1                   # para "minmax"
  sigma_low: 3.0             # para "sigma"
  sigma_high: 3.0            # para "sigma"
  remove_temp_files: true

metadata:
  output_file: "images_data.csv"

qc: # quality checks
  reduction_images: true
  combined_images: true